DROP USER CB CASCADE;
DROP USER CC CASCADE;
DROP ROLE CBROLE;
DROP DIRECTORY MYDIR; 

CREATE ROLE CBROLE NOT IDENTIFIED;
GRANT ALTER SESSION TO CBROLE;
GRANT CREATE DATABASE LINK TO CBROLE;
GRANT CREATE SESSION TO CBROLE;
GRANT CREATE PROCEDURE TO CBROLE;
GRANT CREATE SEQUENCE TO CBROLE;
GRANT CREATE TABLE TO CBROLE;
GRANT CREATE TRIGGER TO CBROLE;
GRANT CREATE TYPE TO CBROLE;
GRANT CREATE JOB TO CBROLE;
GRANT CREATE ANY DIRECTORY TO CBROLE;
GRANT EXECUTE ON UTL_FILE TO CBROLE;
GRANT EXECUTE ON DBMS_LOCK TO CBROLE;
GRANT EXECUTE ON DBMS_RANDOM TO CBROLE;
GRANT EXECUTE ON DBMS_NETWORK_ACL_ADMIN TO CBROLE;

CREATE USER CB IDENTIFIED BY CB DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER CB QUOTA UNLIMITED ON USERS;
GRANT CBROLE TO CB;

CREATE USER CC IDENTIFIED BY CC DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER CC QUOTA UNLIMITED ON USERS;
GRANT CBROLE TO CC;
GRANT EXECUTE ON DBMS_LOCK TO CB;

CREATE DIRECTORY MYDIR AS '/home/oracle/sgbd';

GRANT READ, WRITE ON DIRECTORY MYDIR TO CB;
GRANT READ, WRITE ON DIRECTORY MYDIR TO CC;


--CREATE DATABASE LINK CB_LINK CONNECT TO CB IDENTIFIED BY CB USING 'CB';
--CREATE DATABASE LINK CC_LINK CONNECT TO CC IDENTIFIED BY CC USING 'CC';