BEGIN
	DBMS_SCHEDULER.CREATE_JOB
	(
		JOB_NAME => 'JOB_ARCH_PROG',
		JOB_TYPE => 'STORED_PROCEDURE',
		JOB_ACTION => 'ARCH_PROG',
		START_DATE => SYSTIMESTAMP,
		REPEAT_INTERVAL => 'FREQ=Daily',
		ENABLED => TRUE,
		COMMENTS => 'Archivage des projections'
	);
END;
/