BEGIN
	DBMS_SCHEDULER.CREATE_JOB
	(
		JOB_NAME => 'JOB_AJOUT_ALL_PROG',
		JOB_TYPE => 'STORED_PROCEDURE',
		JOB_ACTION => 'AJOUT_PROG_PACKAGE.JOB_AJOUT_ALL_PROG',
		START_DATE => SYSTIMESTAMP,
		REPEAT_INTERVAL => 'FREQ=Daily;BYHOUR=0;BYMINUTE=1;BYSECOND=0',
		ENABLED => TRUE,
		COMMENTS => 'Scanne des demandes de projection'
	);
END;
/
