CREATE TABLE MOVIES OF XMLType 
XMLType STORE AS OBJECT RELATIONAL
XMLSCHEMA "http://cc/movie.xsd"
ELEMENT "movie"
VARRAY "XMLDATA"."GENRES"."GENRE"
	STORE AS TABLE GENRES ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."DIRECTORS"."DIRECTOR"
	STORE AS TABLE DIRECTORS ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)))
VARRAY "XMLDATA"."ACTORS"."ACTOR"
	STORE AS TABLE ACTORS ((PRIMARY KEY (NESTED_TABLE_ID, SYS_NC_ARRAY_INDEX$)));

CREATE TABLE COPIES OF XMLType
XMLTYPE STORE AS OBJECT RELATIONAL
XMLSCHEMA "http://cc/copy.xsd"
ELEMENT "copy";
   
CREATE TABLE PROJECTIONS OF XMLType
XMLTYPE STORE AS OBJECT RELATIONAL
XMLSCHEMA "http://cc/projection.xsd"
ELEMENT "projection";

CREATE TABLE ARCHIVAGES OF XMLType
XMLTYPE STORE AS OBJECT RELATIONAL
XMLSCHEMA "http://cc/archivage.xsd"
ELEMENT "archivage";

CREATE TABLE PANIERS OF XMLType
XMLTYPE STORE AS OBJECT RELATIONAL
XMLSCHEMA "http://cc/panier.xsd"
ELEMENT "panier";


CREATE TABLE FEEDBACKS OF XMLType
XMLTYPE STORE AS OBJECT RELATIONAL
XMLSCHEMA "http://cc/feedback.xsd"
ELEMENT "feedback";

CREATE TABLE SALLES OF XMLType
XMLTYPE STORE AS OBJECT RELATIONAL
XMLSCHEMA "http://cc/salle.xsd"
ELEMENT "salle";

CREATE TABLE SEANCES OF XMLType
XMLTYPE STORE AS OBJECT RELATIONAL
XMLSCHEMA "http://cc/seance.xsd"
ELEMENT "seance";

CREATE SEQUENCE sequence_seance INCREMENT BY 1 MAXVALUE 99999 NOCYCLE;
CREATE SEQUENCE sequence_salle INCREMENT BY 1 MAXVALUE 99999 NOCYCLE;



ALTER TABLE movies
ADD CONSTRAINT pk_movies PRIMARY KEY (XMLDATA."ID_MOVIE");

ALTER TABLE copies
ADD CONSTRAINT pk_copies PRIMARY KEY (XMLDATA."ID_MOVIE", XMLDATA."NUM");

ALTER TABLE copies
ADD CONSTRAINT fk$movie FOREIGN KEY (XMLDATA."ID_MOVIE") REFERENCES movies(XMLDATA."ID_MOVIE");

ALTER TABLE salles
ADD CONSTRAINT pk$salle PRIMARY KEY (XMLDATA."ID_SALLE");

ALTER TABLE projections
ADD CONSTRAINT fk$salle FOREIGN KEY (XMLDATA."NUM_SALLE") REFERENCES salles(XMLDATA."ID_SALLE");

ALTER TABLE seances
ADD CONSTRAINT pk$seances PRIMARY KEY (XMLDATA."ID_SEANCE");

ALTER TABLE seances
ADD CONSTRAINT fk$seances FOREIGN KEY (XMLDATA."ID_PROJECTION") REFERENCES projections(XMLDATA."ID_PROJECTION");

ALTER TABLE projections
ADD CONSTRAINT pk$projections PRIMARY KEY (XMLDATA."ID_PROJECTION");

ALTER TABLE copies
ADD CONSTRAINT pk$copies PRIMARY KEY (XMLDATA."ID_MOVIE", XMLDATA."NUM");

ALTER TABLE projections
ADD CONSTRAINT fk$copies FOREIGN KEY (XMLDATA."ID_MOVIE", XMLDATA."ID_COPY") REFERENCES copies(XMLDATA."ID_MOVIE", XMLDATA."NUM");
